name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        java: [ 1.8 ]
        os: [ ubuntu-latest ]
        experimental: [ false ]
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - if: matrix.os == 'ubuntu-latest'
        run: sudo gem install fontist

      - if: matrix.os == 'windows-latest'
        run: gem install rake --force

      - if: matrix.os != 'ubuntu-latest'
        run: gem install fontist

      - run: |
          fontist update
          fontist manifest-install --confirm-license .github/mscorefonts.yml

      - uses: actions/cache@v2
        with:
          path: ~/.fontist
          key: fontist-${{ runner.os }}
          restore-keys: fontist-${{ runner.os }}

      # - if: matrix.os == 'windows-latest'
      #   run: choco install --no-progress make

      # Generate test PDFs
      - run: mvn test

      - run: |
          docker run -d -p 8080:8080 -v ./target:/home/folder verapdf/rest:latest
          sleep 5
          curl -F "url=file:///home/folder/G.191.pdf" localhost:8080/api/validate/url/A-3A
